import {
  dimension,
  door,
  gasLine,
  horizontalHvacDuct,
  hvacDuctTransition,
  hvacEquipment,
  hvacJoistReturn,
  hvacRefrigerantLine,
  joist,
  plumbingDrain,
  plumbingEquipment,
  slidingDoor,
  soffit,
  space,
  stairs,
  verticalHvacDuct,
  wall,
  wallCabinet,
  waterValve,
  windowOpening,
} from "./helpers.ts";
import type { FloorPlan } from "./types.ts";

const existing = {
  status: "existing" as const,
  confidence: "approximate" as const,
};
const proposed = {
  status: "proposed" as const,
  confidence: "approximate" as const,
};

const exteriorWall = 8;
const interiorWall = 5;

const joistWidth = 2.25;
const joistClearGaps = [
  9.5, 9.5, 9.5, 9.5, 7.5, 0, 10, 7.25, 0, 9.75,
  9.5, 8, 15.25, 13.5, 13.75, 12.5, 14.25, 13.5, 13.5, 13.5,
  13.5, 13.5, 13.5, 15, 0, 10.25, 7, 0, 17.5, 13,
  13.5, 13.25, 14, 13.5, 13.5, 13.5, 13.5, 13.5, 13.5, 13.5,
] as const;

const joistNorthEdges = joistClearGaps.reduce<number[]>(
  (edges, gap) => [...edges, edges.at(-1)! + joistWidth + gap],
  [8 / 2 + 9.25],
);

const bathroomMainJoistNumbers = [1, 3, 5, 8, 11] as const;
const officeClearGapsAfterJoistFive = [9.75, 9.5, 9.5, 10, 9.5, 4.75, 12, 16.5, 17] as const;
const officeJoistNorthEdges = officeClearGapsAfterJoistFive.reduce<number[]>(
  (edges, gap) => [...edges, edges.at(-1)! + joistWidth + gap],
  [...joistNorthEdges.slice(0, 5)],
);

function joistRunAt(northEdge: number) {
  const centerX = northEdge + joistWidth / 2;
  const eastEnd = centerX < 125 ? 8 / 2 : 26 + 8 / 2;
  const westEnd = 267 - (centerX < 477 ? 5 / 2 : 8 / 2);
  return { centerX, eastEnd, westEnd };
}

export const pocPlan = {
  id: "basement-renovation-plan",
  title: "Basement Renovation Plan",
  subtitle: "Final layout with optional construction scope",
  units: "inches",
  origin: "upper-left",
  orientation: { north: "left" },
  warning: "Planning diagram — verify all measurements and code requirements on site.",
  framing: {
    defaultWallHeight: 96,
    studSpacing: 16,
    studSize: "2x4",
    topPlateCount: 1,
    bottomPlateCount: 1,
    bottomPlateTreated: true,
    wasteFactor: 0.1,
    stockLength: 96,
  },
  walls: [
    wall({ id: "north-exterior-wall", label: "North exterior wall", from: [0, 571], to: [0, 0], thickness: exteriorWall, interiorSide: "right", ...proposed }),
    wall({ id: "east-wall-north-cap", label: "East wall north cap", from: [0, 0], to: [125, 0], thickness: exteriorWall, interiorSide: "right", ...proposed }),
    wall({ id: "northeast-jog-wall", label: "Northeast jog wall", from: [125, 0], to: [125, 26], thickness: exteriorWall, interiorSide: "right", ...proposed }),
    wall({ id: "east-exterior-wall", label: "East exterior wall", from: [125, 26], to: [556, 26], thickness: exteriorWall, interiorSide: "right", ...proposed }),
    wall({ id: "south-exterior-wall", label: "South exterior wall", from: [556, 26], to: [556, 267], thickness: exteriorWall, interiorSide: "right", ...proposed }),
    wall({ id: "storage-west-wall", label: "Utility room west wall — south segment", from: [556, 267], to: [477, 267], thickness: exteriorWall, interiorSide: "right", ...proposed }),
    wall({ id: "furnace-room-south-wall", label: "Utility room west wall — retained segment", from: [477, 267], to: [375, 267], thickness: interiorWall, interiorSide: "right", ...existing }),
    wall({ id: "stair-jog-wall", label: "Finished stair jog wall", from: [375, 267], to: [375, 303], thickness: exteriorWall, interiorSide: "right", ...existing }),
    wall({ id: "stair-west-wall", label: "Finished stair wall", from: [375, 303], to: [196, 303], thickness: exteriorWall, interiorSide: "right", ...existing }),
    wall({ id: "finished-landing-office-jog-wall", label: "Finished landing wall beside Office", from: [196, 303], to: [196, 327], thickness: exteriorWall, interiorSide: "right", ...existing }),
    wall({ id: "office-south-wall", label: "Office south wall", from: [196, 327], to: [196, 529], thickness: exteriorWall, interiorSide: "right", ...proposed }),
    wall({ id: "office-west-jog-wall", label: "Office west jog wall", from: [196, 529], to: [124, 529], thickness: exteriorWall, interiorSide: "right", dimensionSide: "right", ...proposed }),
    wall({ id: "office-bump-south-wall", label: "Office bump south wall", from: [124, 529], to: [124, 571], thickness: exteriorWall, interiorSide: "right", ...proposed }),
    wall({ id: "office-west-wall", label: "Office west wall", from: [124, 571], to: [0, 571], thickness: exteriorWall, interiorSide: "right", ...proposed }),
    wall({
      id: "office-closet-divider-wall",
      label: "Office closet divider wall",
      from: [124, 529],
      to: [0, 529],
      thickness: interiorWall,
      interiorSide: "right",
      dimensionSide: "right",
      status: "proposed",
      confidence: "approximate",
      note: "Continues the office-west-jog-wall north to form an approximately 3-foot-6-inch-deep closet.",
    }),

    wall({ id: "main-west-divider", label: "Main area west divider", from: [0, 267], to: [375, 267], thickness: interiorWall, interiorSide: "right", ...existing }),
    wall({ id: "office-east-divider", label: "Finished bathroom and landing wall", from: [0, 327], to: [196, 327], thickness: interiorWall, interiorSide: "right", ...existing }),
    wall({ id: "bathroom-south-wall", label: "Finished bathroom and landing wall", from: [129, 267], to: [129, 327], thickness: interiorWall, interiorSide: "right", ...existing }),
    wall({ id: "furnace-room-north-wall", label: "Utility room north wall — retained segment", from: [375, 267], to: [375, 222], thickness: interiorWall, interiorSide: "right", ...existing }),
    wall({ id: "utility-room-north-wall-east-extension", label: "Utility room north wall — east extension", from: [375, 222], to: [375, 186], thickness: interiorWall, interiorSide: "right", note: "Nominal 36-inch eastward extension; verify the final wall line on site.", ...proposed }),
    wall({ id: "utility-room-east-wall", label: "Utility room east wall", from: [375, 186], to: [556, 186], thickness: interiorWall, interiorSide: "right", note: "Proposed wall aligned with the east edge of the combined supply-and-return soffit.", ...proposed }),
    wall({ id: "furnace-room-east-wall", label: "Former Furnace Room east wall", from: [375, 222], to: [477, 222], thickness: interiorWall, interiorSide: "left", status: "remove", confidence: "approximate", note: "Remove the existing wall and its double-door opening when the Utility Room is expanded east." }),
    wall({ id: "storage-north-wall", label: "Storage north wall", from: [465, 26], to: [465, 186], thickness: interiorWall, interiorSide: "right", note: "Proposed wall shifted a nominal 12 inches north and shortened at the new Utility Room east wall; verify the final wall line on site.", ...proposed }),
    wall({ id: "furnace-room-storage-wall", label: "Former Furnace Room and Storage divider", from: [477, 222], to: [477, 267], thickness: interiorWall, interiorSide: "right", status: "remove", confidence: "approximate", note: "Remove this finished divider so the Utility Room can continue south to the exterior wall." }),
  ],
  spaces: [
    space({
      id: "main-open-area",
      label: "Main open area",
      polygon: [[0, 0], [125, 0], [125, 26], [465, 26], [465, 186], [375, 186], [375, 267], [0, 267]],
      labelAt: [230, 132],
      note: "Large open area on the east side of the house; room use has not been assigned.",
      ...existing,
    }),
    space({
      id: "storage",
      label: "Storage",
      polygon: [[465, 26], [556, 26], [556, 186], [465, 186]],
      labelAt: [517, 106],
      note: "Remaining Storage footprint after the Utility Room expands into its west side.",
      ...proposed,
    }),
    space({
      id: "furnace-room",
      label: "Utility Room",
      polygon: [[375, 186], [556, 186], [556, 267], [375, 267]],
      labelAt: [505, 213],
      note: "Expanded Utility Room containing the furnace, water heater, electrical panels, and networking cabinet.",
      ...proposed,
    }),
    space({
      id: "bathroom",
      label: "Bathroom",
      polygon: [[0, 267], [129, 267], [129, 327], [0, 327]],
      labelAt: [64, 302],
      note: "Five-foot-deep band shown on the source sketch.",
      ...existing,
    }),
    space({
      id: "office",
      label: "Office",
      polygon: [[0, 327], [196, 327], [196, 529], [0, 529]],
      labelAt: [98, 428],
      note: "Office area after the proposed closet is enclosed.",
      status: "proposed",
      confidence: "approximate",
    }),
    space({
      id: "office-closet",
      label: "Closet",
      polygon: [[0, 529], [124, 529], [124, 571], [0, 571]],
      labelAt: [62, 541],
      note: "Approximately 10 feet 4 inches wide by 3 feet 6 inches deep; verify dimensions on site.",
      status: "proposed",
      confidence: "approximate",
    }),
    space({
      id: "stair-landing",
      label: "Landing",
      polygon: [[129, 267], [187, 267], [187, 303], [196, 303], [196, 327], [129, 327]],
      labelAt: [160, 300],
      note: "Irregular landing geometry inferred from the sketch.",
      ...existing,
    }),
    space({
      id: "under-stair-storage",
      label: "Stair Storage",
      polygon: [[268, 267], [375, 267], [375, 303], [268, 303]],
      labelAt: [321.5, 285],
      note: "Approximate accessible storage footprint beneath the upper half of the stair run.",
      ...existing,
    }),
  ],
  soffits: [
    soffit({
      id: "main-supply-return-soffit",
      label: "Combined supply and return trunk soffit",
      polygon: [[0, 186], [375, 186], [375, 267], [0, 267]],
      note: "One full-width rectangular enclosure from the Utility Room north wall to the north exterior wall. Its east edge aligns with utility-room-east-wall and it encloses both main ceiling trunks. Bottom elevation and framing details are unknown; verify on site.",
      ...proposed,
    }),
  ],
  doors: [
    door({ id: "bathroom-door", label: "Bathroom door", wallId: "main-west-divider", offset: 96, width: 32, hinge: "end", swing: "inward", ...existing, status: "proposed" }),
    door({ id: "main-stair-door", label: "Main area stair door", wallId: "main-west-divider", offset: 144, width: 32, hinge: "end", swing: "outward", ...existing, status: "proposed" }),
    door({ id: "under-stair-storage-door", label: "Under-stair storage door", wallId: "main-west-divider", offset: 340, width: 32, hinge: "end", swing: "outward", status: "proposed", confidence: "exact" }),
    door({ id: "office-door", label: "Office door", wallId: "office-east-divider", offset: 147, width: 32, hinge: "end", swing: "inward", ...existing }),
    door({ id: "furnace-room-double-door-north-leaf", label: "Former Furnace Room double door — north leaf", wallId: "furnace-room-east-wall", offset: 21, width: 30, hinge: "start", swing: "inward", status: "remove", confidence: "approximate", note: "Remove with the former Furnace Room east wall." }),
    door({ id: "furnace-room-double-door-south-leaf", label: "Former Furnace Room double door — south leaf", wallId: "furnace-room-east-wall", offset: 51, width: 30, hinge: "end", swing: "inward", status: "remove", confidence: "approximate", note: "Remove with the former Furnace Room east wall." }),
    door({ id: "utility-room-door", label: "Utility Room door", wallId: "utility-room-east-wall", offset: 43, width: 36, hinge: "end", swing: "outward", status: "proposed", confidence: "approximate", note: "Nominal 36-inch single door aligned with the aisle between the furnace and water heater. Hinges are on the south side. Door and rough-opening height are unknown; verify the soffit relationship, equipment clearances, and code requirements on site." }),
    door({ id: "storage-door", label: "Storage door", wallId: "storage-north-wall", offset: 120, width: 32, hinge: "end", swing: "outward", note: "Shifted a nominal 4 inches east from its prior location, leaving an approximately 8-inch wall segment at the new Utility Room corner; verify framing and trim clearance on site.", ...proposed }),
  ],
  slidingDoors: [
    slidingDoor({
      id: "office-closet-sliding-door",
      label: "Office closet bypass doors",
      wallId: "office-closet-divider-wall",
      offset: 26,
      width: 72,
      panels: 2,
      operation: "bypass",
      note: "Centered two-panel bypass sliding doors; not accordion-style folding doors.",
      status: "proposed",
      confidence: "approximate",
    }),
  ],
  windows: [
    windowOpening({ id: "east-wall-window-north", label: "East wall window — north", wallId: "east-exterior-wall", offset: 70, width: 47, note: "Measured frame width and offset from the northeast jog.", ...existing }),
    windowOpening({ id: "east-wall-window-south", label: "East wall window — south", wallId: "east-exterior-wall", offset: 279, width: 47, note: "Measured frame width and offset from the northeast jog.", ...existing }),
    windowOpening({ id: "north-wall-window-east", label: "North wall window — east", wallId: "north-exterior-wall", offset: 367.5, width: 48, note: "Approximate 48-inch width. Moved west from the original sketch trace so the opening overlaps the plan footprint of main-supply-ceiling-trunk-20 by approximately 4 inches.", ...existing }),
    windowOpening({ id: "north-wall-office-window", label: "North wall office window", wallId: "north-exterior-wall", offset: 112, width: 47, note: "Placed approximately 112 inches east of the office-west-wall junction.", ...existing }),
  ],
  lights: [
    // Lighting will be added as a separate system layer after the base plan is verified.
  ],
  switches: [
    // Wall devices will be added when the electrical layout is mapped.
  ],
  wallCabinets: [
    wallCabinet({
      id: "south-wall-west-electrical-panel",
      label: "West electrical panel",
      cabinetType: "breaker-panel",
      wallId: "south-exterior-wall",
      referenceWallId: "storage-west-wall",
      offset: 12,
      width: 15.25,
      bottomAboveFloor: 45,
      height: 27,
      note: "Existing recessed breaker panel near the west end of the south exterior wall. Measurements are approximate; the cabinet occupies the stud cavity and its depth is intentionally not modeled.",
      ...existing,
    }),
    wallCabinet({
      id: "south-wall-east-electrical-panel",
      label: "East electrical panel",
      cabinetType: "breaker-panel",
      wallId: "south-exterior-wall",
      referenceWallId: "storage-west-wall",
      offset: 27.5,
      width: 15.25,
      bottomAboveFloor: 45,
      height: 27,
      note: "Existing recessed breaker panel matching the west panel. Its west edge is approximately 0.25 inches east of the west panel frame.",
      ...existing,
    }),
    wallCabinet({
      id: "south-wall-networking-cabinet",
      label: "Networking cabinet",
      cabinetType: "networking",
      wallId: "south-exterior-wall",
      referenceWallId: "storage-west-wall",
      offset: 42.5,
      width: 15.5,
      bottomAboveFloor: 29,
      height: 43,
      note: "Existing recessed low-voltage networking cabinet. Height is normalized to approximately 43 inches so its top aligns near 72 inches with both breaker panels; the outer frame overlaps the east panel by approximately 0.25 inches.",
      ...existing,
    }),
  ],
  waterValves: [
    waterValve({
      id: "main-water-valve",
      label: "Main Water Valve",
      wallId: "office-west-jog-wall",
      offset: 54,
      referenceWallId: "office-south-wall",
      valveType: "main-water",
      enclosureWidth: 14,
      enclosureBottomAboveFloor: 20,
      enclosureHeight: 14,
      enclosureStatus: "proposed",
      labelDistance: 34,
      dimensionSide: "right",
      dimensionDistance: 48,
      note: "Existing valve; approximate proposed recessed enclosure centered between studs. Verify all dimensions and enclosure requirements on site.",
      ...existing,
    }),
    waterValve({
      id: "sprinkler-water-valve",
      label: "Sprinkler Water Valve",
      wallId: "office-west-wall",
      offset: 48,
      referenceWallId: "office-bump-south-wall",
      valveType: "sprinkler-water",
      enclosureWidth: 14,
      enclosureBottomAboveFloor: 20,
      enclosureHeight: 24,
      enclosureStatus: "proposed",
      labelDistance: 18,
      dimensionSide: "left",
      dimensionDistance: 27,
      note: "Existing sprinkler shutoff; approximate proposed recessed enclosure centered between studs. Verify all dimensions and enclosure requirements on site.",
      ...existing,
    }),
  ],
  plumbingDrains: [
    plumbingDrain({
      id: "bathroom-tub-shower-drain-rough-in",
      label: "Bathroom tub/shower drain rough-in",
      fixture: "tub-shower",
      at: [20, 320.25],
      diameter: 2.5,
      heightAboveFloor: 8,
      capStatus: "capped",
      pipeColor: "white",
      note: "Existing capped white floor penetration. Center measured 16 inches from the interior face of north-exterior-wall and approximately 4.25 inches east of the bathroom-facing side of office-east-divider. Fixture identity is inferred from the apparent rough-in location; verify on site.",
      ...existing,
    }),
    plumbingDrain({
      id: "bathroom-toilet-drain-rough-in",
      label: "Bathroom toilet drain rough-in",
      fixture: "toilet",
      at: [53, 310.5],
      diameter: 3.5,
      heightAboveFloor: 2.5,
      capStatus: "capped",
      pipeColor: "white",
      note: "Existing capped white floor penetration. Center measured approximately 49 inches from the interior face of north-exterior-wall and approximately 14 inches east of the bathroom-facing side of office-east-divider. Fixture identity is based on the field survey; verify on site.",
      ...existing,
    }),
    plumbingDrain({
      id: "bathroom-sink-drain-rough-in",
      label: "Bathroom sink drain rough-in",
      fixture: "sink",
      at: [94.5, 317.25],
      diameter: 2.5,
      heightAboveFloor: 10.5,
      capStatus: "capped",
      pipeColor: "white",
      note: "Existing capped white floor penetration. Center measured approximately 32 inches north of the bathroom-facing side of bathroom-south-wall and approximately 7.25 inches east of the bathroom-facing side of office-east-divider. Fixture identity is based on the field survey; verify on site.",
      ...existing,
    }),
    plumbingDrain({
      id: "bathroom-unknown-black-drain-rough-in",
      label: "Bathroom unidentified black floor penetration",
      fixture: "unknown",
      at: [122, 311],
      diameter: 5.5,
      heightAboveFloor: 3,
      capStatus: "capped",
      pipeColor: "black",
      note: "Existing capped black floor penetration of unknown function. Center measured approximately 4.5 inches north of the bathroom-facing side of bathroom-south-wall and approximately 13.5 inches east of the bathroom-facing side of office-east-divider. Do not infer a fixture or connection without on-site verification.",
      ...existing,
    }),
  ],
  plumbingEquipment: [
    plumbingEquipment({
      id: "furnace-room-water-heater",
      label: "Existing water heater",
      equipmentType: "water-heater",
      shape: "cylinder",
      center: [464, 254],
      diameter: 20,
      height: 59,
      note: "Existing standard cylindrical water heater inside the expanded Utility Room. The 20-inch plan diameter is a deliberately approximate symbol footprint rather than a measured tank size; the field-estimated height is approximately 59 inches.",
      ...existing,
    }),
  ],
  gasLines: [
    gasLine({
      id: "gas-service-entry-office-closet-to-main-room",
      label: "Gas service entry through Office closet",
      from: [4, 564.5],
      waypoints: [[17.875, 564.5]],
      to: [17.875, 247],
      placement: "joist-bay",
      fromEndpoint: "service-entry",
      note: "Approximate service entry from the north side in the northwest Office closet. The closet run is approximately 2.5 inches east of the interior face of office-west-wall. After passing through the first joist, the nearest outside edge of the west-to-east gas pipe is measured approximately 1.5 inches south of the south face of main-ceiling-joist-01, and the pipe outside diameter is approximately 1.75 inches. The resulting modeled centerline is 2.375 inches south of that joist face. The pipe is observed low in the joist bay, approximately 1 to 2 inches above the joist bottom; whether that field reference is to the pipe edge or centerline remains unmeasured. Repeated field measurements found approximately 8 inches minimum clear from the top of the gas pipe to the underside of the subfloor, with approximately 9 to 10 inches clear in several locations. The run continues through the finished Office and Bathroom bands to the first visible Main Room T. Confirm the concealed entry point and preserve independent support and clearance for adjacent services on site.",
      ...existing,
    }),
    gasLine({
      id: "gas-main-room-stove-branch",
      label: "Gas branch to upstairs stove",
      from: [17.875, 247],
      to: [4, 247],
      placement: "below-joists",
      toEndpoint: "wall-termination",
      note: "Branch at the first Main Room T, approximately 20 inches east of main-west-divider. It drops only enough to run north beneath the joists and is intentionally terminated at north-exterior-wall; the concealed rise to the upstairs stove is not traced.",
      ...existing,
    }),
    gasLine({
      id: "gas-main-room-east-run",
      label: "Gas main east to return-trunk edge",
      from: [17.875, 247],
      to: [17.875, 236],
      placement: "unknown",
      toEndpoint: "drop",
      note: "Approximate eastbound main from the stove T to 2 inches east of the easternmost face of main-return-ceiling-trunk. At the east end it drops to approximately 5 inches below the joists before turning south.",
      ...existing,
    }),
    gasLine({
      id: "gas-main-room-south-run",
      label: "Gas main south beside return trunk",
      from: [17.875, 236],
      to: [335.25, 236],
      placement: "below-joists",
      offsetBelowJoists: 5,
      note: "Approximate straight southbound run parallel to main-return-ceiling-trunk. Its south T is about 38 inches north of furnace-room-north-wall and aligns in the bay between doubled main ceiling joists 25–26 and single joist 27.",
      ...existing,
    }),
    gasLine({
      id: "gas-fireplace-branch-joist-bay",
      label: "Gas branch to fireplace",
      from: [335.25, 236],
      to: [335.25, 83],
      placement: "joist-bay",
      fromEndpoint: "rise",
      toEndpoint: "rise",
      note: "At the Main Room south T, this branch rises into the ceiling and elbows east. It runs with doubled joists 25–26 to its north and single joist 27 approximately 2 inches to its south, then rises toward the fireplace approximately 53 inches west of the interior face of east-exterior-wall.",
      ...existing,
    }),
    gasLine({
      id: "gas-main-to-furnace-room",
      label: "Gas main into Utility Room",
      from: [335.25, 236],
      to: [376, 236],
      placement: "below-joists",
      offsetBelowJoists: 5,
      note: "Continuation south from the fireplace T through the retained furnace-room-north-wall segment, ending approximately 1 inch inside the Utility Room.",
      ...existing,
    }),
    gasLine({
      id: "gas-furnace-room-drop-below-return",
      label: "Utility Room gas drop below return",
      from: [376, 236],
      to: [382, 232],
      placement: "equipment-room",
      toEndpoint: "drop",
      note: "Immediately inside the Utility Room the pipe elbows downward at a slight angle toward the former double-door wall. The approximately 2-foot descent is represented symbolically at the endpoint and clears the return assembly across the furnace front; its exact elevation is inaccessible and unmeasured.",
      ...existing,
    }),
    gasLine({
      id: "gas-furnace-room-manifold-feed",
      label: "Utility Room gas manifold feed",
      from: [382, 232],
      to: [423.5, 232],
      placement: "equipment-room",
      toEndpoint: "drop",
      note: "Approximate low run to the original Utility Room T, placed about 6 inches south of the furnace footprint. A branch descends here to another T approximately 33 inches above the floor, continues about 6 inches lower, and connects to the basement furnace. The unusual final fitting is intentionally omitted.",
      ...existing,
    }),
    gasLine({
      id: "gas-second-floor-furnace-branch",
      label: "Gas branch to second-floor furnace",
      from: [423.5, 232],
      to: [434.25, 251.5],
      placement: "equipment-room",
      toEndpoint: "rise",
      note: "Conceptual plan projection of the branch that rises to within approximately 4 inches of the ceiling, then elbows southwest toward joists-33-34-east-wall-exhaust-10. Its ceiling rise is approximately 5 inches south of the vent's outer edge and 5 inches east of the vent's west endpoint before continuing through the ceiling to the second-floor furnace. Verify the concealed route on site.",
      ...existing,
    }),
    gasLine({
      id: "gas-water-heater-branch",
      label: "Gas branch to water heater",
      from: [423.5, 232],
      to: [465, 232],
      placement: "equipment-room",
      toEndpoint: "appliance",
      note: "Approximate continuation south from the original Utility Room T to within about 1 foot of the retained furnace-room-south-wall segment, where it drops and connects to the nearby water heater. The final low fitting and unmeasured tank connection are intentionally not traced.",
      ...existing,
    }),
  ],
  stairs: [
    stairs({
      id: "main-stair-run",
      label: "Main stair run",
      from: [187, 285],
      to: [349, 285],
      width: 36,
      risers: 14,
      direction: "up",
      planBreakOffset: 81,
      note: "Run, width, riser count, and midpoint plan break are approximate traces from the sketch.",
      ...existing,
    }),
  ],
  joists: [
    ...joistNorthEdges.map((northEdge, index) => {
      const number = index + 1;
      const { centerX, eastEnd, westEnd } = joistRunAt(northEdge);
      const alignmentNote = number === 17
        ? "Approximately aligns with the left edge of east-wall-window-north."
        : number === 32
          ? "Approximately aligns with the left edge of east-wall-window-south."
          : undefined;
      return joist({
        id: `main-ceiling-joist-${String(number).padStart(2, "0")}`,
        label: `Main ceiling joist ${number}`,
        number,
        from: [centerX, eastEnd],
        to: [centerX, westEnd],
        width: joistWidth,
        note: number === 1
          ? "North edge measured approximately 9.25 inches from the interior face of north-exterior-wall."
          : alignmentNote,
        ...existing,
      });
    }),
    ...bathroomMainJoistNumbers.map((mainNumber) => {
      const northEdge = joistNorthEdges[mainNumber - 1];
      const centerX = northEdge + joistWidth / 2;
      return joist({
        id: `bathroom-ceiling-joist-${String(mainNumber).padStart(2, "0")}`,
        label: `Bathroom ceiling joist at main ${mainNumber}`,
        number: mainNumber,
        from: [centerX, 267 + interiorWall / 2],
        to: [centerX, 327 - interiorWall / 2],
        width: joistWidth,
        note: mainNumber === 1
          ? "Aligned to main joists 1, 3, 5, 8, and 11. Main positions 2, 4, 6, 7, 9, 10, and 12 are absent in the Bathroom."
          : mainNumber === 11
            ? "Main positions 9 and 10 are absent at the cold-air intake; framing resumes here at main position 11."
            : `Aligned with main ceiling joist ${mainNumber}.`,
        ...existing,
      });
    }),
    ...officeJoistNorthEdges.map((northEdge, index) => {
      const number = index + 1;
      const centerX = northEdge + joistWidth / 2;
      return joist({
        id: `office-ceiling-joist-${String(number).padStart(2, "0")}`,
        label: `Office ceiling joist ${number}`,
        number,
        from: [centerX, 327 + interiorWall / 2],
        to: [centerX, centerX < 124 ? 571 - exteriorWall / 2 : 529 - exteriorWall / 2],
        width: joistWidth,
        note: number <= 5 ? `Aligned with main ceiling joist ${number}.` : undefined,
        ...existing,
      });
    }),
  ],
  hvacEquipment: [
    hvacEquipment({
      id: "existing-furnace",
      label: "Existing furnace",
      equipmentType: "furnace",
      center: [408.5, 247],
      width: 18,
      depth: 30,
      rotation: 0,
      note: "Approximate 18-by-30-inch outer footprint measured on site. The north edge is approximately 22 inches from the interior face of furnace-room-north-wall. Its plan position was adjusted 2.5 inches to align the furnace, vertical return trunk, and ceiling return trunk; verify the west clearance on site. Equipment height has not been measured.",
      ...existing,
    }),
  ],
  hvacDucts: [
    verticalHvacDuct({
      id: "furnace-return-vertical-trunk",
      label: "Furnace return vertical trunk",
      airflowRole: "return",
      shape: "rectangular",
      center: [392.5, 250],
      width: 12,
      depth: 24,
      rotation: 0,
      bottomAboveFloor: 0,
      topAboveFloor: 91,
      note: "Approximate 12-by-24-inch return box immediately north of the furnace. Its plan centerline aligns with the main return ceiling trunk, and it appears to run from the concrete floor to the underside of the ceiling joists.",
      ...existing,
    }),
    horizontalHvacDuct({
      id: "main-return-ceiling-trunk",
      label: "Main return ceiling trunk",
      airflowRole: "return",
      shape: "rectangular",
      from: [392.5, 250],
      to: [84.5, 250],
      width: 24,
      height: 10,
      bottomAboveFloor: 81,
      note: "Approximate 24-inch-wide by 10-inch-tall return trunk at the ceiling. The west edge has about 2.5 inches clear to the visible face of main-west-divider. It runs north from the furnace return riser to 11.5 inches beyond the north edge of bathroom-door.",
      ...existing,
    }),
    horizontalHvacDuct({
      id: "furnace-return-riser-south-wall-run-08",
      label: "Furnace return riser to south wall — approximately 8 inch round",
      airflowRole: "return",
      shape: "round",
      from: [392.5, 238],
      waypoints: [[392.5, 234]],
      to: [474.5, 234],
      bendStyle: "round",
      diameter: 8,
      bottomAboveFloor: 75,
      note: "Existing approximately 8-inch-diameter round return takeoff from the east face of furnace-return-vertical-trunk. It immediately elbows south beneath the Utility Room supply trunk, runs approximately 82 inches to the former furnace-room-storage-wall line, then elbows upward as an approximately 8-inch round continuation into the floor above. The divider is proposed for removal; the plan route and 75-inch underside elevation are approximate field estimates, so verify the concealed endpoint and elevation on site.",
      ...existing,
    }),
    horizontalHvacDuct({
      id: "joists-33-34-east-wall-exhaust-10",
      label: "Utility Room east-wall exhaust — approximately 10 inch round",
      airflowRole: "exhaust",
      shape: "round",
      from: [424.25, 256.5],
      to: [424.25, 22],
      diameter: 10,
      bottomAboveFloor: 91,
      note: "Existing approximately 10-inch-diameter round HVAC vent contained in the clear bay between main-ceiling-joist-33 and main-ceiling-joist-34. Its open Utility Room end is approximately 8 inches east of the interior face of the retained furnace-room-south-wall segment. It runs east above the Utility Room, passes close to the centerline of east-wall-window-south, and exits through east-exterior-wall. The 91-inch underside uses the measured joist-bottom elevation to record that the vent stays within the bay; verify its exact vertical position and function on site.",
      ...existing,
    }),
    verticalHvacDuct({
      id: "furnace-supply-vertical-plenum",
      label: "Furnace supply vertical plenum",
      airflowRole: "supply",
      shape: "rectangular",
      center: [408.5, 251.75],
      width: 16.5,
      depth: 20.5,
      rotation: 0,
      bottomAboveFloor: 58,
      topAboveFloor: 91,
      note: "Approximate 16.5-by-20.5-inch supply plenum centered across the furnace width with its west/back edge aligned to the furnace. It rises from the approximately 58-inch-tall furnace to the 91-inch underside of the ceiling joists.",
      ...existing,
    }),
    horizontalHvacDuct({
      id: "main-supply-ceiling-trunk-24",
      label: "Main supply ceiling trunk — 24 inch",
      airflowRole: "supply",
      shape: "rectangular",
      from: [412.25, 219.5],
      waypoints: [[412.25, 207.5]],
      to: [161.5, 207.5],
      bendStyle: "round",
      width: 24,
      height: 8,
      bottomAboveFloor: 83,
      note: "Approximate 24-by-8-inch ceiling supply trunk. It turns north at the former furnace-room-east-wall line with a rounded outside corner, crosses the expanded Utility Room, and continues to 2 inches north of the north edge of main-ceiling-joist-15.",
      ...existing,
    }),
    horizontalHvacDuct({
      id: "main-supply-ceiling-trunk-20",
      label: "Main supply ceiling trunk — 20 inch",
      airflowRole: "supply",
      shape: "rectangular",
      from: [150, 209.5],
      to: [4, 209.5],
      width: 20,
      height: 8,
      bottomAboveFloor: 83,
      note: "Approximate 20-by-8-inch ceiling supply trunk. It begins at the south edge of main-ceiling-joist-14 and continues north with zero clear gap to the interior face of north-exterior-wall.",
      ...existing,
    }),
    horizontalHvacDuct({
      id: "north-bay-upper-floor-supply-08",
      label: "North bay upper-floor supply — 8 inch round",
      airflowRole: "supply",
      shape: "round",
      from: [8.625, 209.5],
      to: [8.625, 4],
      diameter: 8,
      bottomAboveFloor: 93,
      note: "Existing 8-inch-diameter round supply branch centered in the 9.25-inch clear bay between north-exterior-wall and main-ceiling-joist-01, leaving approximately 0.625 inch clear on each side. It takes off from the top of main-supply-ceiling-trunk-20, rises through an elbow so its underside is about 2 inches above the rectangular trunk top, and runs east to the interior face of east-wall-north-cap. The wall-end connection to the upper floor has not yet been documented; verify the route and elevations on site.",
      ...existing,
    }),
    horizontalHvacDuct({
      id: "joists-01-02-north-wall-window-east-supply-06",
      label: "Joists 1–2 north-wall east window supply — 6 inch round",
      airflowRole: "supply",
      shape: "round",
      from: [20.25, 209.5],
      to: [20.25, 179.5],
      diameter: 6,
      bottomAboveFloor: 93,
      note: "Proposed approximately 6-inch-diameter round supply branch centered in the 9.5-inch clear bay between main-ceiling-joist-01 and main-ceiling-joist-02. It takes off from main-supply-ceiling-trunk-20 and ends at a ceiling register aligned with the midpoint of north-wall-window-east, approximately 16.25 inches inside the north wall face. Final diameter, register selection, airflow, takeoff damper, and elevation require Manual J/Manual D design and on-site verification.",
      status: "proposed",
      confidence: "approximate",
    }),
    horizontalHvacDuct({
      id: "joists-01-02-north-wall-office-window-supply-06",
      label: "Joists 1–2 north-wall Office window supply — 6 inch round",
      airflowRole: "supply",
      shape: "round",
      from: [20.25, 209.5],
      to: [20.25, 435.5],
      diameter: 6,
      bottomAboveFloor: 93,
      note: "Proposed approximately 6-inch-diameter rigid round supply branch centered in the 9.5-inch clear bay between main-ceiling-joist-01 and main-ceiling-joist-02. It uses a separate directional takeoff and accessible balancing damper at main-supply-ceiling-trunk-20, runs west through the Bathroom and Office above gas-service-entry-office-closet-to-main-room, and ends at a ceiling register aligned with the midpoint of north-wall-office-window approximately 16.25 inches inside the north wall face. Field measurements found approximately 8 inches minimum clear from the top of the gas pipe to the underside of the subfloor, with approximately 9 to 10 inches clear in several locations. Final diameter, vertical separation, independent support, register selection, airflow, fitting geometry, and elevation require Manual J/Manual D design and on-site verification.",
      status: "proposed",
      confidence: "approximate",
    }),
    horizontalHvacDuct({
      id: "joists-04-05-office-closet-supply-08",
      label: "Joists 4–5 office closet supply — 8 inch round",
      airflowRole: "supply",
      shape: "round",
      from: [55.5, 209.5],
      waypoints: [[55.5, 312], [43.75, 312]],
      to: [43.75, 567],
      bendStyle: "round",
      diameter: 8,
      bottomAboveFloor: 93,
      note: "Existing approximately 8-inch-diameter round supply branch taking off from the west side of main-supply-ceiling-trunk-20 between main ceiling joists 4 and 5. It immediately rises above the trunk and elbows west in that bay, passes through the bathroom, then uses two elbows near the office side of the bathroom to shift north into the bay between main positions 3 and 4. Bathroom joist position 4 is absent. The branch crosses into the Office between office ceiling joists 3 and 4 and continues through the proposed Closet to the interior face of office-west-wall. The bathroom dogleg, elevation, and endpoint connection are approximate; verify on site.",
      ...existing,
    }),
    horizontalHvacDuct({
      id: "joists-05-06-short-flex-supply-08",
      label: "Joists 5–6 short flexible supply — approximately 8 inch",
      airflowRole: "supply",
      shape: "round",
      from: [66.25, 209.5],
      to: [66.25, 235],
      diameter: 8,
      bottomAboveFloor: 93,
      note: "Existing short flexible supply takeoff from the west side of main-supply-ceiling-trunk-20 between main ceiling joists 5 and 6. The flexible duct is approximately 8 inches in nominal diameter and appears compressed to fit the approximately 7.5-inch clear joist bay. Its visible plan projection extends approximately 15.5 inches beyond the supply trunk face, ending about 3 inches short of the nearest face of main-return-ceiling-trunk, where it bends upward. The route above that point has not been documented; verify diameter, deformation, and elevation on site.",
      ...existing,
    }),
    horizontalHvacDuct({
      id: "joists-11-12-bathroom-south-supply-05",
      label: "Joists 11–12 Bathroom south supply — approximately 5 inch round",
      airflowRole: "supply",
      shape: "round",
      from: [115.25, 209.5],
      to: [115.25, 297],
      diameter: 5,
      bottomAboveFloor: 93,
      note: "Proposed approximately 5-inch-diameter rigid round supply branch centered in the 9.5-inch clear bay between main-ceiling-joist-11 and main-ceiling-joist-12. It uses a directional takeoff and accessible balancing damper at main-supply-ceiling-trunk-20, crosses above main-return-ceiling-trunk, continues west across main-west-divider above the Bathroom doorway, and ends at a ceiling register near the east-to-west center of the Bathroom's south side. The register center is approximately 11.25 inches north of the Bathroom-facing side of bathroom-south-wall and remains separated from north-trunk-bathroom-office-panned-return by bathroom-ceiling-joist-11. Verify joist-end blocking, top-plate and door-header clearance, final diameter, airflow, register selection, fitting geometry, and elevation through Manual J/Manual D design and on-site inspection.",
      status: "proposed",
      confidence: "approximate",
    }),
    horizontalHvacDuct({
      id: "joists-16-17-upper-floor-supply-08",
      label: "Joists 16–17 upper-floor supply — 8 inch round",
      airflowRole: "supply",
      shape: "round",
      from: [188, 207.5],
      to: [188, 30],
      diameter: 8,
      bottomAboveFloor: 93,
      note: "Existing 8-inch-diameter round supply branch centered in the 12.5-inch clear bay between main-ceiling-joist-16 and main-ceiling-joist-17, leaving approximately 2.25 inches clear on each side. It follows the same observed pattern as the north-bay branch: a top takeoff and elbow from main-supply-ceiling-trunk-24, then an eastbound run to the interior face of east-exterior-wall. The diameter and elevation are treated as approximate from the similar-pattern field description; verify on site.",
      ...existing,
    }),
    horizontalHvacDuct({
      id: "joists-16-17-office-south-wall-supply-06",
      label: "Joists 16–17 office south wall supply — 6 inch round",
      airflowRole: "supply",
      shape: "round",
      from: [188, 207.5],
      to: [188, 525],
      diameter: 6,
      bottomAboveFloor: 93,
      note: "Existing approximately 6-inch-diameter round supply branch taking off from the west side of main-supply-ceiling-trunk-24 between main ceiling joists 16 and 17. It is separate from the 8-inch eastbound branch in the same bay. It immediately rises above the supply trunk, elbows west, crosses above main-return-ceiling-trunk, and continues over the Landing. In the Office it runs between office-ceiling-joist-14 and office-south-wall to the interior corner at office-west-jog-wall. Diameter, elevation, and endpoint connection are approximate; verify on site.",
      ...existing,
    }),
    horizontalHvacDuct({
      id: "joists-18-19-east-wall-window-north-supply-06",
      label: "Joists 18–19 east-wall north window supply — 6 inch round",
      airflowRole: "supply",
      shape: "round",
      from: [219.75, 207.5],
      to: [219.75, 38.125],
      diameter: 6,
      bottomAboveFloor: 93,
      note: "Proposed approximately 6-inch-diameter round supply branch centered in the 13.5-inch clear bay between main-ceiling-joist-18 and main-ceiling-joist-19. It takes off from main-supply-ceiling-trunk-24 and ends at a ceiling register approximately 8.125 inches inside the east wall face. The joist-bay centerline is approximately 1.25 inches south of the midpoint of east-wall-window-north. Final diameter, register selection, airflow, takeoff damper, and elevation require Manual J/Manual D design and on-site verification.",
      status: "proposed",
      confidence: "approximate",
    }),
    horizontalHvacDuct({
      id: "joists-23-24-upper-floor-supply-08",
      label: "Joists 23–24 upper-floor supply — 8 inch round",
      airflowRole: "supply",
      shape: "round",
      from: [298.5, 207.5],
      to: [298.5, 30],
      diameter: 8,
      bottomAboveFloor: 93,
      note: "Existing 8-inch-diameter round supply branch centered in the 13.5-inch clear bay between main-ceiling-joist-23 and main-ceiling-joist-24, leaving approximately 2.75 inches clear on each side. It follows the same observed pattern as the north-bay branch: a top takeoff and elbow from main-supply-ceiling-trunk-24, then an eastbound run to the interior face of east-exterior-wall. The diameter and elevation are treated as approximate from the similar-pattern field description; verify on site.",
      ...existing,
    }),
    horizontalHvacDuct({
      id: "joists-29-30-short-supply-06",
      label: "Joists 29–30 short supply — 6 inch round",
      airflowRole: "supply",
      shape: "round",
      from: [362, 204.5],
      to: [362, 126.5],
      diameter: 6,
      bottomAboveFloor: 93,
      note: "Existing 6-inch-diameter round supply branch between main-ceiling-joist-29 and main-ceiling-joist-30. Its south edge is placed approximately 3.5 inches from the north edge of joist 30, using the midpoint of the observed 3-to-4-inch clearance. It takes off from the top of main-supply-ceiling-trunk-24, represented by an approximate 9-inch westward extension into the trunk footprint, then extends the measured 69 inches east from the trunk's east face to its observed endpoint. The endpoint condition and elevation have not been directly measured; verify on site.",
      ...existing,
    }),
    horizontalHvacDuct({
      id: "joist-32-short-side-takeoff-supply-06",
      label: "Joist 32 short side-takeoff supply — 6 inch round",
      airflowRole: "supply",
      shape: "round",
      from: [400.625, 195.5],
      to: [405, 187.5],
      diameter: 6,
      bottomAboveFloor: 84,
      note: "Existing short 6-inch-diameter round takeoff at the rounded east side of main-supply-ceiling-trunk-24, directly beneath main-ceiling-joist-32. It angles approximately 8 inches east and slightly south, then turns nearly vertically upward just beyond joist 32. The plan geometry is intentionally approximate and records presence rather than a measured fitting shape; verify on site.",
      ...existing,
    }),
    horizontalHvacDuct({
      id: "supply-elbow-to-joist-37-under-joist-run-08",
      label: "Supply elbow to joist 37 under-joist run — 8 inch round",
      airflowRole: "supply",
      shape: "round",
      from: [412.25, 207.5],
      waypoints: [[420.25, 199.5]],
      to: [487.5, 199.5],
      bendStyle: "round",
      diameter: 8,
      bottomAboveFloor: 83,
      note: "Existing 8-inch-diameter round supply segment leaving the rounded main supply elbow at approximately 45 degrees, then turning south beneath the joists toward main-ceiling-joist-37. Its east edge is kept approximately parallel with the east edge of the main supply trunk. At joist 37 it elbows upward into the adjacent joist bay; the fitting geometry and elevation are approximate and must be verified on site.",
      ...existing,
    }),
    horizontalHvacDuct({
      id: "joists-34-35-east-wall-window-south-supply-06",
      label: "Joists 34–35 east-wall south window supply — 6 inch round",
      airflowRole: "supply",
      shape: "round",
      from: [440.25, 199.5],
      to: [440.25, 38.125],
      diameter: 6,
      bottomAboveFloor: 93,
      note: "Proposed approximately 6-inch-diameter round supply branch centered in the 13.5-inch clear bay between main-ceiling-joist-34 and main-ceiling-joist-35. It takes off with a directional fitting and accessible balancing damper from supply-elbow-to-joist-37-under-joist-run-08, rises into the joist bay, and ends at a ceiling register approximately 8.125 inches inside the east wall face near east-wall-window-south. Final diameter, fitting geometry, register selection, airflow, clearance from joists and the adjacent HVAC vent, and elevation require Manual J/Manual D design and on-site verification.",
      status: "proposed",
      confidence: "approximate",
    }),
    horizontalHvacDuct({
      id: "joists-37-38-upper-floor-supply-08",
      label: "Joists 37–38 upper-floor supply — 8 inch round",
      airflowRole: "supply",
      shape: "round",
      from: [487.5, 199.5],
      to: [487.5, 30],
      diameter: 8,
      bottomAboveFloor: 93,
      note: "Existing 8-inch-diameter continuation of supply-elbow-to-joist-37-under-joist-run-08. After rising at joist 37, it elbows east and runs centered in the 13.5-inch clear bay between main-ceiling-joist-37 and main-ceiling-joist-38, leaving approximately 2.75 inches clear on each side, to the interior face of east-exterior-wall. The in-bay elevation is approximate; verify on site.",
      ...existing,
    }),
  ],
  hvacJoistReturns: [
    hvacJoistReturn({
      id: "joists-23-25-west-wall-panned-return",
      label: "Joists 23–25 west-wall panned return",
      polygon: [[291.75, 238], [322.5, 238], [322.5, 264.5], [291.75, 264.5]],
      joistIds: ["main-ceiling-joist-23", "main-ceiling-joist-24", "main-ceiling-joist-25"],
      note: "Existing sheet-metal panning over the two adjacent bays between main ceiling joists 23–24 and 24–25. It connects through the top of main-return-ceiling-trunk and covers the small gap from the trunk's west edge to main-west-divider. The continuation upward within the joist or wall cavities is inferred from the field observation and remains unverified.",
      ...existing,
    }),
    hvacJoistReturn({
      id: "joists-19-21-west-wall-panned-return",
      label: "Joists 19–21 west-wall panned return",
      polygon: [[228.75, 238], [258, 238], [258, 264.5], [228.75, 264.5]],
      joistIds: ["main-ceiling-joist-19", "main-ceiling-joist-20", "main-ceiling-joist-21"],
      note: "Existing sheet-metal panning over the two adjacent bays between main ceiling joists 19–20 and 20–21. It follows the same observed pattern as joists-23-25-west-wall-panned-return: a connection through the top of main-return-ceiling-trunk and panning across the small west-side gap to main-west-divider. The concealed upward continuation is inferred and remains unverified.",
      ...existing,
    }),
    hvacJoistReturn({
      id: "north-trunk-bathroom-office-panned-return",
      label: "North trunk through Bathroom and Office panned return",
      polygon: [[86.75, 238], [94, 238], [94, 267], [108.25, 267], [108.25, 327], [95.75, 327], [95.75, 417], [86.25, 417], [86.25, 327], [86.75, 327]],
      joistIds: ["main-ceiling-joist-08", "main-ceiling-joist-09", "bathroom-ceiling-joist-08", "bathroom-ceiling-joist-11", "office-ceiling-joist-07", "office-ceiling-joist-08"],
      note: "Existing panned return beginning at the north end of main-return-ceiling-trunk in the approximate main joist 8–9 bay. It runs west through main-west-divider, widens across the Bathroom from joist position 8 to 11 because positions 9 and 10 are absent, then narrows to the aligned single bay between Office joists 7 and 8. The Office section extends approximately 90 inches west from office-east-divider to y=417, near the east edge of north-wall-office-window, where it appears to turn upward into the floor above. Joist assignment and concealed connections are approximate; verify on site.",
      ...existing,
    }),
  ],
  hvacDuctTransitions: [
    hvacDuctTransition({
      id: "furnace-supply-east-expansion",
      label: "Furnace supply east expansion",
      airflowRole: "supply",
      shape: "rectangular",
      polygon: [[400.25, 241.5], [400.25, 219.5], [424.25, 219.5], [416.75, 241.5]],
      fromWidth: 16.5,
      toWidth: 24,
      height: 8,
      bottomAboveFloor: 83,
      fixedEdge: "north",
      note: "Approximate asymmetric supply transition from the top plenum through the east furnace-room wall. The north edge remains straight while the south edge expands 7.5 inches to reach a 24-inch width.",
      ...existing,
    }),
    hvacDuctTransition({
      id: "main-supply-reduction-24-to-20",
      label: "Main supply reduction — 24 to 20 inch",
      airflowRole: "supply",
      shape: "rectangular",
      polygon: [[161.5, 219.5], [161.5, 195.5], [150, 199.5], [150, 219.5]],
      fromWidth: 24,
      toWidth: 20,
      height: 8,
      bottomAboveFloor: 83,
      fixedEdge: "west",
      note: "Approximate asymmetric reduction beginning 2 inches north of the north edge of main-ceiling-joist-15 and reaching 20 inches wide at the south edge of main-ceiling-joist-14. The west edge remains straight while the east edge angles inward.",
      ...existing,
    }),
  ],
  hvacRefrigerantLines: [
    hvacRefrigerantLine({
      id: "furnace-to-south-exterior-refrigerant-line",
      label: "Furnace to south exterior refrigerant line",
      from: [408.5, 247],
      waypoints: [[477, 243], [552, 243]],
      to: [560, 243],
      wallPenetrationBelowJoists: 4,
      support: "joist-underside",
      exteriorTurn: "up",
      note: "Existing refrigerant line shown with a deliberately simplified straight conceptual route inside the expanded Utility Room. It crosses the former furnace-room-storage-wall line approximately 24 inches east of the west/back wall, about 4 inches below the joist bottoms, then rises to attach beneath the joists and continues south within the Utility Room. At south-exterior-wall it curves upward and exits toward the exterior AC units. Exact fittings, line-set size, Utility Room routing, and exterior continuation have not been measured.",
      ...existing,
    }),
  ],
  circuits: [
    // Circuits are intentionally empty until a real electrical layer is provided.
  ],
  dimensions: [
    dimension({ id: "overall-north-south-span", label: "Overall north-south span", from: [0, 0], to: [556, 0], offset: 22, detail: "overall", text: "≈ 46′-4″", ...existing }),
    dimension({ id: "overall-east-west-span", label: "Overall east-west span", from: [556, 0], to: [556, 571], offset: 22, detail: "overall", text: "≈ 47′-7″", ...existing }),
  ],
} satisfies FloorPlan;
